{% set name = "napari-spatialdata" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0560241652639f4728e19ac315afc94ed938306ed6aacf8920b4df388f4e9a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - anndata
    - magicgui
    - napari
    - numba
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image
    - squidpy
    - loguru

test:
  imports:
    - napari_spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scverse/napari-spatialdata.git
  summary: Interactive visualization of spatial omics data with napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giovp
    - goanpeca
    - jaimergp
