{% set name = "napari-spatialdata" %}
{% set version = "0.5.4.post0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3c0c2dbff707b845e6f0f6e77cd99300db20ebbc1c971d7f77a4473260038dc9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - anndata >=0.9.1
    - click
    - cycler
    - dask-core >=2024.4.1
    - geopandas
    - loguru
    - matplotlib-base
    - napari >=0.4.19.post1
    - napari-matplotlib
    - numba
    - numpy
    - packaging
    - pandas
    - pillow
    - python >={{ python_min }}
    - qtpy
    - scanpy
    - scipy
    - scikit-learn
    - shapely
    - spatialdata >=0.2.1
    - superqt
    - typing-extensions >=4.8.0
    - vispy
    - xarray
    - xarray-datatree

test:
  imports:
    - napari_spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - pyqt

about:
  home: https://pypi.org/project/napari-spatialdata
  summary: Interactive visualization of spatial omics data with napari
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/napari-spatialdata

extra:
  recipe-maintainers:
    - giovp
    - goanpeca
    - jaimergp
    - LucaMarconato
    - melonora
