{% set name = "napari-spatialdata" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: decadbc0a8b72ce02c1fd57869111b1ada8a024b9fc2f53f4afb47dccf8a89a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - anndata
    - cycler   # Imported but not in requirements
    - dask-core  # Imported but not in requirements
    - geopandas  # Imported but not in requirements
    - loguru
    # - magicgui  # Required but not imported
    - matplotlib-base  # Imported but not in requirements
    - napari
    - napari-matplotlib  # Imported but not in requirements
    - numba
    - numpy
    - packaging  # Imported but not in requirements
    - pandas  # Imported but not in requirements
    - python >=3.9
    - qtpy
    # - scikit-image  # Required but not imported
    - scikit-learn  # Imported but not in requirements
    - spatialdata
    - scipy  # Imported but not in requirements
    # - squidpy  # Required but not imported
    - superqt  # Imported but not in requirements
    - vispy  # Imported but not in requirements

test:
  imports:
    - napari_spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-spatialdata
  summary: Interactive visualization of spatial omics data with napari
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/napari-spatialdata

extra:
  recipe-maintainers:
    - giovp
    - goanpeca
    - jaimergp
